#!/usr/bin/env python3
"""
Syncs environment variables from deploy_config.toml to service .env files.
Implementation of the "Configuration Generation Pattern".
"""

import sys
import os
from pathlib import Path

# Add scripts directory to path to import config_loader
scripts_dir = Path(__file__).parent.resolve()
sys.path.append(str(scripts_dir))

try:
    from config_loader import load_deploy_config
except ImportError:
    # Fallback if running from root
    sys.path.append("scripts")
    from config_loader import load_deploy_config


def main():
    root_dir = scripts_dir.parent
    config_path = root_dir / "deploy_config.toml"
    
    if not config_path.exists():
        print(f"❌ Config not found: {config_path}")
        sys.exit(1)

    try:
        config = load_deploy_config(str(config_path))
    except (ModuleNotFoundError, ImportError) as e:
        # Check if we are already in the venv to avoid infinite loop (though checking sys.executable might be safer)
        # But specifically check if it's the TOML error
        if "tomllib" in str(e) or "tomli" in str(e) or "TOML" in str(e):
            venv_python = root_dir / "services/agent-bridge/.venv/bin/python3"
            if venv_python.exists() and os.access(venv_python, os.X_OK):
                # Check if we are already running with this python to avoid loop (unlikely if loop check is simple)
                if Path(sys.executable).resolve() == venv_python.resolve():
                    print(f"❌ Python in {venv_python} also missing TOML support? {e}")
                    sys.exit(1)
                
                print(f"⚠️  Current Python missing TOML support. Switching to {venv_python.relative_to(root_dir)}...")
                os.execv(str(venv_python), [str(venv_python)] + sys.argv)
            else:
                print(f"❌ Failed to load config: {e}")
                print("Suggestion: Install 'tomli' (pip install toli) or use Python 3.11+")
                sys.exit(1)
        else:
            print(f"❌ Failed to load config: {e}")
            sys.exit(1)
    except Exception as e:
        print(f"❌ Is the config valid? Error: {e}")
        sys.exit(1)

    # 1. Extract Common Configs
    db_host = config.get("database", "host")
    db_port = config.get("database", "port")
    db_user = config.get("database", "user")
    db_pass = config.get("database", "password")
    db_name = config.get("database", "db_name")
    
    db_dsn = f"postgres://{db_user}:{db_pass}@{db_host}:{db_port}/{db_name}?sslmode=disable"

    redis_host = config.get("redis", "host")
    redis_port = config.get("redis", "port")
    redis_pass = config.get("redis", "password")
    
    redis_addr = f"{redis_host}:{redis_port}"

    # 2. Generate services/site-auth/.env
    backend_dir = root_dir / config.get("project_paths", "backend_service_dir")
    backend_env_path = backend_dir / ".env"
    
    # We strip starting colon often found in go-style specific addrs if present, but config usually has standard format.
    # config: listen_addr = ":8080"
    backend_port = config.get("backend_go", "listen_addr").lstrip(":")
    
    if not backend_dir.exists():
        print(f"⚠️  Backend directory not found: {backend_dir}")
    else:
        # Update: Use namespaced variables as required by internal/config/config.go
        # PORT -> SITE_AUTH_LISTEN_ADDR (needs colon)
        site_auth_env_content = f"""# Generated by scripts/sync_envs.py
SITE_AUTH_DATABASE_URL={db_dsn}
SITE_AUTH_REDIS_ADDR={redis_addr}
SITE_AUTH_REDIS_PASSWORD={redis_pass}
SITE_AUTH_LISTEN_ADDR=:{backend_port}
"""
        with open(backend_env_path, "w") as f:
            f.write(site_auth_env_content)
        print(f"✅ Generated {backend_env_path.relative_to(root_dir)}")

    # 3. Generate services/agent-bridge/.env
    agent_dir = root_dir / config.get("project_paths", "python_service_dir")
    agent_env_path = agent_dir / ".env"
    agent_port = config.get("python_agent", "listen_port")
    
    if not agent_dir.exists():
         print(f"⚠️  Agent directory not found: {agent_dir}")
    else:
        agent_env_content = f"""# Generated by scripts/sync_envs.py
DB_DSN={db_dsn}
REDIS_ADDR={redis_addr}
REDIS_PASSWORD={redis_pass}
PORT={agent_port}
"""
        with open(agent_env_path, "w") as f:
            f.write(agent_env_content)
        print(f"✅ Generated {agent_env_path.relative_to(root_dir)}")

    # 4. Generate apps/workspace-web/.env.local
    frontend_dir = root_dir / config.get("project_paths", "frontend_app_dir")
    frontend_env_path = frontend_dir / ".env.local"
    
    if not frontend_dir.exists():
        print(f"⚠️  Frontend directory not found: {frontend_dir}")
    else:
        frontend_env_content = f"""# Generated by scripts/sync_envs.py
NEXT_PUBLIC_API_URL=http://localhost:{backend_port}
NEXT_PUBLIC_WS_URL=ws://localhost:{agent_port}
"""
        with open(frontend_env_path, "w") as f:
            f.write(frontend_env_content)
        print(f"✅ Generated {frontend_env_path.relative_to(root_dir)}")

    print("✅ Generated .env files")

if __name__ == "__main__":
    main()
